# This Travis-CI file is for testing the state of the MOM6 source code.
# It does NOT test MOM6 solutions.

# This is a not a c-language project but we use the same environment.
language: c
dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - tcsh pkg-config netcdf-bin libnetcdf-dev libnetcdff-dev gfortran
    - mpich libmpich-dev
    - doxygen graphviz flex bison cmake
    - python-numpy python-netcdf4
    - bc

jobs:
  include:
      script:
        - git clone --recursive https://github.com/NOAA-GFDL/MOM6.git
        - cd MOM6/.testing
        - make MKMF_TEMPLATE=linux-ubuntu-xenial-gnu.mk all
