# This Travis-CI file is for testing the state of the MOM6 source code.
# It does NOT test MOM6 solutions.

# This is a not a c-language project but we use the same environment.
language: c
dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - tcsh pkg-config netcdf-bin libnetcdf-dev libnetcdff-dev openmpi-bin libopenmpi-dev gfortran
    - doxygen graphviz flex bison cmake
    - python-numpy python-netcdf4

jobs:
  include:
      script:
        - git clone https://github.com/NOAA-GFDL/MOM6.git
        - cd MOM6/.testing
        - make all
